developer:
  author: ''
  email: ''
options:
  overrideJava: true
  overrideXml: true
  overrideOther: true
settings:
  javaPath: src/main/java
  resourcesPath: src/main/resources
  fileTypes:
    - type: entity
      suffix: Entity
      packageName: com.example.entity
      override: true
    - type: dao
      suffix: Repository
      packageName: com.example.repository
      override: true
    - type: service
      suffix: Service
      packageName: com.example.service
      override: true
    - type: serviceImpl
      suffix: ServiceImpl
      packageName: com.example.service.impl
      override: true
    - type: controller
      suffix: Controller
      packageName: com.example.controller
      override: true
    - type: mapper
      suffix: Mapper
      packageName: mapper
      asSourceCode: false
      override: true
types:
  - shortName: Object
    longName: java.lang.Object
    isDefault: true
    dbTypes: []
  - shortName: Boolean
    longName: java.lang.Boolean
    dbTypes:
      - ^bit
  - shortName: Long
    longName: java.lang.Long
    dbTypes:
      - ^bigint
  - shortName: Integer
    longName: java.lang.Integer
    dbTypes:
      - ^tinyint
      - ^smallint
      - ^mediumint
      - ^int
  - shortName: String
    longName: java.lang.String
    dbTypes:
      - ^char
      - ^varchar
      - ^text
      - ^longtext
      - ^tinytext
  - shortName: BigDecimal
    longName: java.math.BigDecimal
    dbTypes:
      - ^decimal
      - ^numeric
  - shortName: Float
    longName: java.lang.Float
    dbTypes:
      - ^float
  - shortName: Double
    longName: java.lang.Double
    dbTypes:
      - ^double
  - shortName: LocalDateTime
    longName: java.time.LocalDateTime
    dbTypes:
      - ^datetime
      - ^timestamp
  - shortName: LocalDate
    longName: java.time.LocalDate
    dbTypes:
      - ^date
  - shortName: LocalTime
    longName: java.time.LocalTime
    dbTypes:
      - ^time
