[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="date" type="org.joda.time.DateTime" --]
[#-- @ftlvariable name="gen" type="com.github.houkunlin.vo.Variable.static" --]
[#-- @ftlvariable name="settings" type="com.github.houkunlin.config.Settings" --]
[#-- @ftlvariable name="settings.projectPath" type="java.lang.String" --]
[#-- @ftlvariable name="settings.javaPath" type="java.lang.String" --]
[#-- @ftlvariable name="settings.resourcesPath" type="java.lang.String" --]
[#-- @ftlvariable name="developer" type="com.github.houkunlin.config.Developer" --]
[#-- @ftlvariable name="developer.author" type="java.lang.String" --]
[#-- @ftlvariable name="developer.email" type="java.lang.String" --]
[#-- @ftlvariable name="entity" type="com.github.houkunlin.vo.impl.EntityImpl" --]
[#-- @ftlvariable name="entity.name" type="java.util.Map<java.lang.String, com.github.houkunlin.vo.impl.EntityName>" --]
[#-- @ftlvariable name="entity.name.entity" type="com.github.houkunlin.vo.impl.EntityName" --]
[#-- @ftlvariable name="entity.name.service" type="com.github.houkunlin.vo.impl.EntityName" --]
[#-- @ftlvariable name="entity.name.serviceImpl" type="com.github.houkunlin.vo.impl.EntityName" --]
[#-- @ftlvariable name="entity.name.dao" type="com.github.houkunlin.vo.impl.EntityName" --]
[#-- @ftlvariable name="entity.name.controller" type="com.github.houkunlin.vo.impl.EntityName" --]
[#-- @ftlvariable name="entity.name.xml" type="com.github.houkunlin.vo.impl.EntityName" --]
[#-- @ftlvariable name="entity.packages" type="com.github.houkunlin.vo.impl.EntityPackage" --]
[#-- @ftlvariable name="entity.packages.entity" type="com.github.houkunlin.vo.impl.EntityPackageInfo" --]
[#-- @ftlvariable name="entity.packages.service" type="com.github.houkunlin.vo.impl.EntityPackageInfo" --]
[#-- @ftlvariable name="entity.packages.serviceImpl" type="com.github.houkunlin.vo.impl.EntityPackageInfo" --]
[#-- @ftlvariable name="entity.packages.dao" type="com.github.houkunlin.vo.impl.EntityPackageInfo" --]
[#-- @ftlvariable name="entity.packages.controller" type="com.github.houkunlin.vo.impl.EntityPackageInfo" --]
[#-- @ftlvariable name="entity.packages.xml" type="com.github.houkunlin.vo.impl.EntityPackageInfo" --]
[#-- @ftlvariable name="table" type="com.github.houkunlin.vo.impl.TableImpl" --]
[#-- @ftlvariable name="primary" type="com.github.houkunlin.vo.impl.PrimaryInfo" --]
[#-- @ftlvariable name="fields" type="java.util.List<com.github.houkunlin.vo.impl.EntityFieldImpl>" --]
[#-- @ftlvariable name="columns" type="java.util.List<com.github.houkunlin.vo.impl.TableColumnImpl>" --]
